data_dir: DATA_DIR_PATH
batch_size: 64
n_leading_observations: 5
crop_side_length: 128
load_from_hdf5: true
num_workers: 16
remove_duplicate_features: false
features_to_keep: null
add_binary_fire_mask: true