data_dir: DATA_DIR_PATH
batch_size: 64
n_leading_observations: 5
crop_side_length: 128
load_from_hdf5: true
num_workers: 16
remove_duplicate_features: false
add_binary_fire_mask: true
# -1 and -2 are the indices of the binary and time-indicating fire mask respectively
features_to_keep: [0,1,2,-2,-1]