# pytorch_lightning==2.0.1
seed_everything: 0
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: src.models.SMPModel
  init_args:
    encoder_name: resnet18
    n_channels: 40
    flatten_temporal_dimension: true
    pos_class_weight: 236
    loss_function: Dice
data:
  data_dir: /Users/hbanafsh/Downloads/HDF5Dataset
  remove_duplicate_features: true
  batch_size: 16  # Example, adjust as needed
  num_workers: 4  # Example, adjust as needed
  crop_side_length: 32  # Example, adjust as needed
  n_leading_observations: 5  # Example, adjust as needed
  n_leading_observations_test_adjustment: 5  # Example, adjust as needed
  load_from_hdf5: true

do_train: true
do_predict: false
do_test: true
